
set_property IOSTANDARD LVCMOS33 [get_ports {seg[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg[0]}]

set_property PACKAGE_PIN T10 [get_ports {seg[6]}]
set_property PACKAGE_PIN R10 [get_ports {seg[5]}]
set_property PACKAGE_PIN K16 [get_ports {seg[4]}]
set_property PACKAGE_PIN K13 [get_ports {seg[3]}]
set_property PACKAGE_PIN P15 [get_ports {seg[2]}]
set_property PACKAGE_PIN T11 [get_ports {seg[1]}]
set_property PACKAGE_PIN L18 [get_ports {seg[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports {state[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {state[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {state[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {state[0]}]
set_property PACKAGE_PIN V11 [get_ports {state[3]}]
set_property PACKAGE_PIN V12 [get_ports {state[2]}]
set_property PACKAGE_PIN V14 [get_ports {state[1]}]
set_property PACKAGE_PIN V15 [get_ports {state[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports clk_100Mhz]
set_property PACKAGE_PIN E3 [get_ports clk_100Mhz]

set_property IOSTANDARD LVCMOS33 [get_ports {anodes[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {anodes[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {anodes[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {anodes[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {anodes[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {anodes[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports play_pause]
set_property IOSTANDARD LVCMOS33 [get_ports reset]
set_property PACKAGE_PIN J15 [get_ports play_pause]
set_property PACKAGE_PIN L16 [get_ports reset]
set_property PACKAGE_PIN T14 [get_ports {anodes[5]}]
set_property PACKAGE_PIN P14 [get_ports {anodes[4]}]
set_property PACKAGE_PIN J14 [get_ports {anodes[3]}]
set_property PACKAGE_PIN T9 [get_ports {anodes[2]}]
set_property PACKAGE_PIN J18 [get_ports {anodes[1]}]
set_property PACKAGE_PIN J17 [get_ports {anodes[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports increment]
set_property PACKAGE_PIN M17 [get_ports increment]
set_property IOSTANDARD LVCMOS33 [get_ports select]
set_property PACKAGE_PIN N17 [get_ports select]
